default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: gschool

development:
  <<: *default
  database: g2-rails-practice-task-list-development

test:
  <<: *default
  database: g2-rails-practice-task-list-test
